language: java
jdk:
  - oraclejdk8
sudo: false
env:
  - TASK=compile
  - TASK=checkstyle
script:
  - if [ "$TASK" = "compile" ];    then ant jar; fi
  - if [ "$TASK" = "checkstyle" ]; then ant checkstyle-jar && ant checkstyle; fi
